# Generated by Django 3.0 on 2021-07-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('longitude', models.IntegerField()),
                ('latitude', models.IntegerField()),
                ('indoor', models.BooleanField()),
                ('numOfCourts', models.IntegerField()),
            ],
        ),
    ]
