# Generated by Django 3.0 on 2021-07-19 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_meetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ownedMeetup', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetup',
            name='park_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetupLocation', to='api.Park'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendingMeetup', to=settings.AUTH_USER_MODEL),
        ),
    ]
